---
swagger: "2.0"
info:
  description: "An API for measurements used in monitoring plant systems."
  version: "1.0.0"
  title: "NFT Experiment"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "sensor"
  description: "Endpoints relating to sensor data"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /allMeasurements:
    post:
      tags:
      - "sensor"
      summary: "Add a set of measurements for temperature, EC, voltage, pH, and rH"
      description: ""
      operationId: "updatePetWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "ec"
        in: "formData"
        description: "Electrical conductivity measurement"
        required: true
        type: "number"
        format: "float"
      - name: "voltage"
        in: "formData"
        description: "Voltage measurement (in volts)"
        required: true
        type: "number"
        format: "float"
      - name: "pH"
        in: "formData"
        description: "pH measurement"
        required: true
        type: "number"
        format: "float"
      - name: "rH"
        in: "formData"
        description: "rH measurement"
        required: true
        type: "number"
        format: "float"
      - name: "wTemp"
        in: "formData"
        description: "WTemperature measurement"
        required: true
        type: "number"
        format: "float"
      - name: "aTemp"
        in: "formData"
        description: "ATemperature measurement"
        required: true
        type: "number"
        format: "float"
      - name: "timestamp"
        in: "formData"
        description: "time the measurements were collected"
        required: true
        type: "string"
        format: "dateTime"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Sensor"
definitions: {}
