---
swagger: "2.0"
info:
  description: "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)\
    \ or HTML."
  version: "1.0.0"
  title: "DataLogger API"
paths:
  /log/{system}:    
    post:
      summary: "Create a new log entry."
      description: "Optional extended description in CommonMark or HTML."
      operationId: "logPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "system"
        in: "path"
        description: "Name of the system this log entry is for"
        required: true
        type: "string"
      - name: "entry"
        in: "body"        
        required: true
        schema:
          $ref: "#/definitions/LogEntry"
      responses:
        204:
          description: "A log entry is successfully made and nothing is returned."
      x-swagger-router-controller: "Default"
    x-swagger-router-controller: "entry"
  /log/{system}/{timestamp}:
    get:
      summary: "Get all logs after the provided timestamp"
      description: "Optional extended description in CommonMark or HTML."
      x-swagger-router-controller: "GetLogs"
      operationId: "logGET"
      produces:
      - "application/json"
      parameters:
      - name: "system"
        in: "path"
        description: "Only log entries for this system will be returned"
        required: true
        type: "string"
        format: "string"
      - name: "timestamp"
        in: "path"        
        description: "Only log entries whose timestamp comes after this one will be returned"
        required: true
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/LogEntry"
definitions:
  LogEntry:
    required:
    - "aTemp"
    - "ec"
    - "pH"
    - "rH"
    - "timestamp"
    - "voltage"
    - "wTemp"
    properties:
      ec:
        type: "number"
        format: "float"
        description: "Electrical conductivity measurement"
      voltage:
        type: "number"
        format: "float"
        description: "Voltage measurement (in volts)"
      pH:
        type: "number"
        format: "float"
        description: "pH measurement"
      rH:
        type: "number"
        format: "float"
        description: "rH measurement"
      wTemp:
        type: "number"
        format: "float"
        description: "Water Temperature measurement"
      aTemp:
        type: "number"
        format: "float"
        description: "Air Temperature measurement"
      timestamp:
        type: "string"
        format: "dateTime"
        description: "Time the measurements were collected"
