---
swagger: "2.0"
info:
  description: "Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/)\
    \ or HTML."
  version: "1.0.0"
  title: "DataLogger API"
paths:
  /log/{system}:    
    post:
      summary: "Create a new log entry."
      description: "Optional extended description in CommonMark or HTML."
      x-swagger-router-controller: "PostLogs"
      operationId: "logPOST"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "system"
        in: "path"
        description: "Name of the system this log entry is for"
        required: true
        type: "string"
      - name: "entry"
        in: "body"        
        required: true
        schema:
          $ref: "#/definitions/Log"
      responses:
        204:
          description: "A log entry is successfully made and nothing is returned."
  /log/all/{timestamp}:
    get:
      summary: "Get all logs after the provided timestamp"
      description: "Optional extended description in CommonMark or HTML."
      x-swagger-router-controller: "GetLogs"
      operationId: "logGET"
      produces:
      - "application/json"
      parameters:      
      - name: "timestamp"
        in: "path"        
        description: "Only log entries whose timestamp comes after this one will be returned"
        required: true
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "successful operation"
          schema:          
            $ref: "#/definitions/Logs"                    
  /log/{system}/{timestamp}:
    get:
      summary: "Get all logs, for the provided system, after the provided timestamp"
      description: "Optional extended description in CommonMark or HTML."
      x-swagger-router-controller: "GetLogs"
      operationId: "logBySystemGET"
      produces:
      - "application/json"
      parameters:
      - name: "system"
        in: "path"
        description: "Only log entries for this system will be returned"
        required: true
        type: "string"
        format: "string"
      - name: "timestamp"
        in: "path"        
        description: "Only log entries whose timestamp comes after this one will be returned"
        required: true
        type: "string"
        format: "date-time"
      responses:
        200:
          description: "successful operation"
          schema:            
            $ref: "#/definitions/Logs"
  /system:
    get:
      summary: "Get the names of all systems that have created log entries."
      description: "Optional extended description in CommonMark or HTML."
      x-swagger-router-controller: "GetSystems"
      operationId: "systemGET"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation" 
          schema:
            $ref: '#/definitions/Systems'

definitions:
  Systems:
    type: "object"
    properties:
      entries:
        type: "array"
        items: 
          type: "string"
        description: "The names of the systems"
  Logs:
    type: "object"
    properties:
      entries:
        type: "array"
        items:
          $ref: '#/definitions/Log'
  Log:
    required:    
    - "sensors"
    - "timestamp"  
    type: "object"
    properties:
      system:        
        type: "string"
      sensors:         
        type: "object"
      timestamp:         
        type: "string"
        format: "dateTime"
    description: "The sensor data, timestamp, and systemID"
